name: lint-datapack
on:
  push:
  workflow_dispatch:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Dependencies - 1
        uses: actions/checkout@v3
        with:
          repository: haiiro2gou/TSB-Patcher
          ref: v0.0.4

      - name: Checkout Dependencies - 2
        uses: actions/checkout@v3
        with:
          repository: ProjectTSB/TheSkyBlessing
          ref: refs/tags/v0.1.6
          path: TSB-master
          sparse-checkout: |
            NaturalMergeSort
            OhMyDat

      - name: Deploy Dependencies
        run: |
          mv -f TSB-master/** ../TSB-Extended
          rm -rf TSB-master/

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: TSB-Extended

      - name: Datapack Linter
        uses: ChenCMD/datapack-linter@v2
        with:
          muteSuccessResult: true
          ignoreLintPathPattern: |
            animated_java:**