name: lint-datapack
on:
    push:
    pull_request:
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true
jobs:
    lint:
        name: lint
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Dependencies
            uses: actions/checkout@v4
            with:
                repository: haiiro2gou/TSB-Patcher
                fetch-depth: 0
                ref: refs/tags/v1.0.1

          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
                path: TSB-Extended

          - name: Datapack Linter
            uses: ChenCMD/datapack-linter@v2
            with:
                muteSuccessResult: true
                ignoreLintPathPattern: |
                    animated_java:**
