name: file-list
on:
  workflow_dispatch:
jobs:
  list:
    name: list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dependencies - 1
        uses: actions/checkout@v3
        with:
          repository: haiiro2gou/TSB-Patcher
          ref: v0.0.4

      - name: Checkout Dependencies - 2
        uses: actions/checkout@v3
        with:
          repository: ProjectTSB/TheSkyBlessing
          ref: refs/tags/v0.1.6
          path: TSB-master
          sparse-checkout: |
            NaturalMergeSort
            OhMyDat
          sparse-checkout-cone-mode: false

      - run: |
          mv -f TSB-master/** ../TSB-Extended
          rm -rf TSB-master/

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: TSB-Extended

      - run: |
          ls -1URH ../**