name: file-list
on:
    workflow_dispatch:
jobs:
    list:
        name: list
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Dependencies
            uses: actions/checkout@v4
            with:
                repository: haiiro2gou/TSB-Patcher
                ref: master

          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
                path: TSB-Extended

          - run: |
                ls -1URH ../**
