name: file-list
on:
  workflow_dispatch:
jobs:
  list:
    name: list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dependencies - 1
        uses: actions/checkout@v3
        with:
          repository: haiiro2gou/TSB-Patcher
          ref: v1.0.0

      - name: Checkout Dependencies - 2
        uses: actions/checkout@v3
        with:
          repository: ProjectTSB/TheSkyBlessing
          ref: refs/tags/v0.1.6
          path: TSB-master
          sparse-checkout: |
            NaturalMergeSort
            OhMyDat

      - name: Deploy Dependencies
        run: |
          mv -f TSB-master/** ../TSB-Extended
          rm -r TSB-master

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: TSB-Extended

      - name: File List
        run: |
          ls -1URH ../**